# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=255)),
                ('email_addresses', models.CharField(default='{"email_addresses": []}', max_length=255)),
                ('phone_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(default='{"contacts": []}', max_length=10000)),
                ('subject', models.CharField(default=0, max_length=255)),
                ('message', models.CharField(default=0, max_length=10000)),
                ('last_notified', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('lifespan', models.IntegerField(default=0)),
                ('expiration', models.IntegerField(default=0)),
                ('expired', models.BooleanField(default=False)),
                ('viewable', models.BooleanField(default=False)),
                ('deletable', models.BooleanField(default=False)),
                ('number_of_notifies', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Profile'),
        ),
    ]
