# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='5b04b271-79ec-41a3-b647-3d8f3bac7963', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='3d1a7775-7ed8-43af-9801-5960a0ed439d', max_length=255),
        ),
    ]
