# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0002_auto_20180401_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='5533ad6f-c6e6-4f69-b3e8-ff8925636ec2', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_addresses',
            field=models.TextField(default='{"email_addresses": []}', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='d92546b4-6df6-4bc2-897a-f18052bef20d', max_length=255),
        ),
    ]
