# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0003_auto_20180401_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='3d3e8e88-2168-4536-8211-98d7c06d204a', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_addresses',
            field=models.TextField(default='{"email_addresses": [null]}', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='f126928a-70d4-47dd-ba60-618d631c450e', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.CharField(default='{"contacts": [null]}', max_length=10000),
        ),
    ]
