# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0003_auto_20180411_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='fbfdcced-3784-4000-ad4d-87851775ddd1', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='386c6c1d-f449-4d92-be42-819adb9c7add', max_length=255, unique=True),
        ),
    ]
