# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0004_auto_20180411_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='741ed669-271b-430e-a60e-77cd320e48a3', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='fcaa479f-6f6d-41b7-a561-3890b5a8fe5d', max_length=255, unique=True),
        ),
    ]
