# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0004_auto_20180401_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='expiration',
            new_name='cutoff',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='f344046e-2a7b-4736-9f5c-326e13f1be66', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_addresses',
            field=models.TextField(default='{"email_addresses": []}', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='21cfeda3-e536-4891-9fa6-565be36dbd8a', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.CharField(default='{"contacts": []}', max_length=10000),
        ),
    ]
