# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0005_auto_20180411_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='0f047f0e-79c7-425a-a335-fa1c3c2577c7', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='4a666a09-3748-4bed-bb04-f4bd8a6acce9', max_length=255, unique=True),
        ),
    ]
