# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0005_auto_20180401_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='26ff58d8-7350-4010-9365-dcf8a62faffb', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='7282e3b5-bdc9-45df-8c33-abdc5bba7f14', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='viewable',
            field=models.BooleanField(default=True),
        ),
    ]
