# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0006_auto_20180411_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='e86cc12d-1ba8-41fa-9029-b14554f6d93d', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='d43ef112-dc5b-437c-9685-60bc848264e0', max_length=255, unique=True),
        ),
    ]
