# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0006_auto_20180402_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='bec5e1dd-e0b4-498a-88f6-f04b9cfac61d', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='e59cd7d7-2356-4c88-ac84-77ec8b0a8173', max_length=255, unique=True),
        ),
    ]
