# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0008_auto_20180411_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='ddbf28dd-ec7c-4847-b875-595b53be03be', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='3a5cc4a6-0876-46f7-8ded-a3c74a584353', max_length=255, unique=True),
        ),
    ]
