# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0008_auto_20180402_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='e1dae48a-f3dc-4ad8-a3ff-21e8a450a103', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='36a293fc-6b95-4cde-905e-740c3e67ddab', max_length=255, unique=True),
        ),
    ]
