# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0009_auto_20180402_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='81f679fb-fe9b-4a9e-91b8-8d9edd9e8ce7', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='66d5ac26-5b9d-48cb-ad2f-2b832270e0b4', max_length=255, unique=True),
        ),
    ]
