# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0010_auto_20180402_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='<function uuid4 at 0x000001830ACEC598>', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='<function uuid4 at 0x000001830ACEC598>', max_length=255, unique=True),
        ),
    ]
