# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0011_auto_20180402_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='faa2c4db-23b7-4a4d-9b2d-b7b3c04da190', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='aabec999-f1f8-4ebb-92fb-9361327b5f78', max_length=255, unique=True),
        ),
    ]
