# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0012_auto_20180402_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='f57eafc5-51de-4553-8462-59adb35e5207', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 17, 21, 24, 105579, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_notified',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 17, 21, 24, 105579, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='0cdd2a3f-9e5b-407b-afc0-59d6f700ad2d', max_length=255, unique=True),
        ),
    ]
