# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0013_auto_20180402_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='03a5df35-b9cd-45bb-bd3c-e5a8000320ff', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_notified',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='3927e0b6-8a63-4948-afb3-8e1744951f1d', max_length=255, unique=True),
        ),
    ]
