# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-07 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0014_auto_20180402_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=0, max_length=255)),
                ('status', models.CharField(default=0, max_length=255)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='last_reminder',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='5b77cdaf-43dc-424d-8e98-c168d876aca5', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='11dac83e-dd1a-435b-8d9c-70e279e05f18', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Message'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Contact'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Contact'),
        ),
    ]
