# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0015_auto_20180407_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_addresses',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='bd166483-fbc0-48e1-80b8-4ba2029efc0f', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='f8b777d0-9408-488f-afd1-912ac0272be1', max_length=255, unique=True),
        ),
    ]
