# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0016_auto_20180409_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='66291dfa-09ed-416b-9b5d-ecf4ad529390', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='a953f06e-37c8-444a-a891-d8d4c18604e3', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Contact'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Message'),
        ),
    ]
