# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0017_auto_20180410_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='a398fb4c-3d6c-419b-b5f8-ca242225324e', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='c6f8dfc4-e241-4cea-9230-490688ace9fd', max_length=255, unique=True),
        ),
    ]
