# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0018_auto_20180410_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='cfa116f1-e7b0-417f-bbf6-72441052338a', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='d2693893-2c52-41ff-a298-c488cc1d40f9', max_length=255, unique=True),
        ),
    ]
