# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(default=0, max_length=255)),
                ('type', models.CharField(default=0, max_length=255)),
                ('identifier', models.CharField(default=0, max_length=255)),
                ('status', models.CharField(default=0, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Recipient')),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='expiration',
            new_name='cutoff',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_addresses',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipients',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='e1e0614f-ad91-4843-9594-e353c7edeb35', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='last_reminder',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='c7b15407-438a-4c6f-a0bc-125edcac303e', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='viewable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Contact'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Message'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Contact'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadman.Contact'),
        ),
    ]
