# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0002_auto_20180411_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='edbb3bd6-e50c-43be-a4bc-520a305a0cf9', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='f7be9db3-2bf2-4c33-868e-f6642f067fa4', max_length=255, unique=True),
        ),
    ]
