# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadman', '0009_auto_20180411_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='77b755de-f81c-4d4b-9272-9f693f5ea3a0', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='83f2fee1-e2fd-44cc-931f-c8676da8fd6c', max_length=255, unique=True),
        ),
    ]
